### PR TITLE
fully upgrade to v6 of @typegoose/typegoose

### PR DESCRIPTION
**Pull request by duro**

### CODE REVIEW

**Comment by dirkbolte** [comment]
I don't get it working for me with typegoose 6 . 

The Class looks like this:
```
@Injectable()
export class UserService {
  constructor(@InjectModel(User) private readonly userModel: ReturnModelType<typeof User>)  {}
  async create(dto) {
    const newUser = new this.userModel({...dto}); // The resulting object is: { _id: "..." }

    // with typegoose: 
    const userModel2 = getModelForClass(User);
    const newUser2 = new userModel({...dto}) // this contains _id + all values of the dto
}
```

**Comment by duro** [comment]
@dirkbolte what do your model definitions look like? And why are you doing another `getModelForClass` rather than relying on the injected model?

Here is what my models looks like:

```
@index('parent', { sparse: true })
export class Organization {
  @prop({ required: true })
  public name: string

  @prop({ default: null })
  public parent: Ref<Organization> | null
}
```

**Comment by dirkbolte** [comment]
My Model:

```
export class User extends Base {
    @prop({lowercase: true, trim: true, required: true, unique: true})
    email: string;
    @prop({required: true})
    firstname: string;
    @prop({required: true})
    lastname: string;
// ... and so forth
}
```

The code in my previous comment was just to illustrate that the injected model doesn't work while in the very same setup, a direct call to typegoose works. It's like nestjs-typegoose returns the model for an empty class.
Also, when I print the schema, the one provided by nestjs-typegoose is basically empty - no prop of the class is in there.

**Comment by duro** [comment]
I think I've seen this happen before in my own testing. It had to do with
having multiple versions of the nestjs packages in my dependency tree. Can
you make sure that is not the case.

**Comment by dirkbolte** [comment]
checked quickly - found a dangling old typegoose module - but removal + wipe + reinstall didn't address it.
I will check whether I can build a standalone test case for this.

**Comment by duro** [comment]
Just heads up, I'm using this branch of my own fork to successfully
integrate this into an existing project:

https://github.com/duro/nestjs-typegoose/tree/dist-6.0

**Pull request merged**
